import type { WebNotification } from "@/types/notification";
import type { ScheduledTask } from "@/types/scheduled-task";
import type { TaskRun } from "@/types/task-run";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();
const minutesAfter = (minutes: number) => new Date(now.getTime() + minutes * 60_000).toISOString();

export const scheduledTasks: ScheduledTask[] = [
  {
    id: "task_001",
    userId: "user_001",
    name: "Morning Daily Brief",
    type: "Daily Brief",
    scheduleType: "Daily",
    cronExpression: "0 8 * * *",
    time: "08:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News", "Weather API"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 70,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(80),
    nextRunAt: minutesAfter(520),
    createdAt: minutesAgo(4000),
    updatedAt: minutesAgo(80),
  },
  {
    id: "task_002",
    userId: "user_001",
    name: "Shopee Sale Monitor",
    type: "Sale Monitor",
    scheduleType: "Hourly",
    cronExpression: "0 * * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Product Prices"],
    gptActions: ["Analyze Priority", "Generate Caption", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 85,
    status: "Running",
    isActive: true,
    lastRunAt: minutesAgo(17),
    nextRunAt: minutesAfter(43),
    createdAt: minutesAgo(3500),
    updatedAt: minutesAgo(17),
  },
  {
    id: "task_003",
    userId: "user_001",
    name: "Weekend Ideas Generator",
    type: "Weekend Ideas",
    scheduleType: "Weekly",
    cronExpression: "0 9 * * 6",
    time: "09:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Weather API", "News"],
    gptActions: ["Summarize", "Recommend Action", "Generate Image Prompt"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 60,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(1440),
    nextRunAt: minutesAfter(2880),
    createdAt: minutesAgo(6000),
    updatedAt: minutesAgo(1440),
  },
  {
    id: "task_004",
    userId: "user_001",
    name: "Important Email Monitor",
    type: "Email Monitor",
    scheduleType: "Hourly",
    cronExpression: "*/30 * * * *",
    time: null,
    timezone: "Asia/Bangkok",
    dataSources: ["Gmail"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications", "Send Telegram"],
    minPriorityScore: 80,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(36),
    nextRunAt: minutesAfter(24),
    createdAt: minutesAgo(7200),
    updatedAt: minutesAgo(36),
  },
  {
    id: "task_005",
    userId: "user_001",
    name: "Concert Alerts Near Me",
    type: "Concert Alerts",
    scheduleType: "Daily",
    cronExpression: "0 20 * * *",
    time: "20:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Concert API"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 75,
    status: "Paused",
    isActive: false,
    lastRunAt: minutesAgo(2880),
    nextRunAt: null,
    createdAt: minutesAgo(7000),
    updatedAt: minutesAgo(1000),
  },
  {
    id: "task_006",
    userId: "user_001",
    name: "Football Recap Nightly",
    type: "World Cup Recap",
    scheduleType: "Daily",
    cronExpression: "0 23 * * *",
    time: "23:00",
    timezone: "Asia/Bangkok",
    dataSources: ["Football API"],
    gptActions: ["Summarize", "Generate Caption", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 65,
    status: "Failed",
    isActive: true,
    lastRunAt: minutesAgo(240),
    nextRunAt: minutesAfter(1140),
    createdAt: minutesAgo(9000),
    updatedAt: minutesAgo(240),
  },
  {
    id: "task_007",
    userId: "user_001",
    name: "Weekend Long Read Picker",
    type: "Weekend Long Read",
    scheduleType: "Weekly",
    cronExpression: "0 10 * * 6",
    time: "10:00",
    timezone: "Asia/Bangkok",
    dataSources: ["News"],
    gptActions: ["Summarize", "Analyze Priority", "Recommend Action"],
    outputChannels: ["Save to Web Dashboard", "Save to Notifications"],
    minPriorityScore: 55,
    status: "Active",
    isActive: true,
    lastRunAt: minutesAgo(3000),
    nextRunAt: minutesAfter(3600),
    createdAt: minutesAgo(9400),
    updatedAt: minutesAgo(3000),
  },
];

export const taskRuns: TaskRun[] = [
  {
    id: "run_001",
    taskId: "task_001",
    status: "success",
    startedAt: minutesAgo(80),
    finishedAt: minutesAgo(79),
    rawInput: {
      news: ["AI tools update", "Market movement summary"],
      weather: "Bangkok is cloudy with afternoon rain risk.",
    },
    gptPrompt: "Summarize and prioritize today's updates for Nimbus Daily.",
    gptOutput: {
      title: "Morning Daily Brief",
      summary: "วันนี้มีข่าว AI และสภาพอากาศที่ควรรู้ เหมาะสำหรับจัดลำดับงานช่วงเช้า",
      priority_score: 82,
      recommended_action: "อ่านข่าว AI สำคัญก่อนเริ่มงาน และเตรียมแผนสำรองถ้าฝนตกช่วงเย็น",
      caption: "สรุปเช้านี้: AI อัปเดตแรง + ฝนมีโอกาสตกช่วงเย็น",
      image_prompt: "9:16 neon SaaS dashboard showing daily AI brief cards, dark glass UI, blue purple glow",
    },
    priorityScore: 82,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_002",
    taskId: "task_002",
    status: "running",
    startedAt: minutesAgo(5),
    finishedAt: null,
    rawInput: {
      products: ["Power bank", "USB-C cable", "Wireless earbuds"],
    },
    gptPrompt: "Analyze product price movement and recommend if deal is worth alerting.",
    gptOutput: {
      title: "Sale Monitor Running",
      summary: "กำลังตรวจสอบราคาสินค้าและความคุ้มค่าของโปรล่าสุด",
      priority_score: 0,
      recommended_action: "รอผลวิเคราะห์จาก GPT",
      caption: null,
      image_prompt: null,
    },
    priorityScore: 0,
    telegramStatus: "not_enabled",
    errorMessage: null,
  },
  {
    id: "run_003",
    taskId: "task_004",
    status: "success",
    startedAt: minutesAgo(36),
    finishedAt: minutesAgo(35),
    rawInput: {
      gmail: ["Vendor invoice reminder", "Security alert", "Meeting summary"],
    },
    gptPrompt: "Summarize important emails and rank priority.",
    gptOutput: {
      title: "Email Monitor Alert",
      summary: "พบอีเมลที่ควรตรวจวันนี้ 2 รายการ ได้แก่ Security alert และ invoice reminder",
      priority_score: 88,
      recommended_action: "เปิด Security alert ก่อน แล้วค่อยตรวจ invoice reminder",
      caption: "มีอีเมลสำคัญที่ควรดูวันนี้ Priority 88/100",
      image_prompt: null,
    },
    priorityScore: 88,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_004",
    taskId: "task_003",
    status: "success",
    startedAt: minutesAgo(1440),
    finishedAt: minutesAgo(1439),
    rawInput: {
      weather: "Weekend weather is clear in the morning.",
      news: ["New cafe opening", "Outdoor market this weekend"],
    },
    gptPrompt: "Generate weekend ideas using weather and local updates.",
    gptOutput: {
      title: "Weekend Ideas",
      summary: "เสาร์นี้เหมาะกับคาเฟ่และตลาดกลางแจ้งช่วงเช้า เลี่ยงช่วงบ่ายถ้าอากาศร้อน",
      priority_score: 74,
      recommended_action: "เลือก 1 คาเฟ่ + 1 กิจกรรม outdoor แล้วบันทึกเป็น plan",
      caption: "ไอเดียเที่ยวเสาร์นี้: คาเฟ่เช้า + ตลาด outdoor แบบชิล ๆ",
      image_prompt: "9:16 lifestyle weekend plan card, modern dark glass dashboard, neon blue purple, Bangkok vibes",
    },
    priorityScore: 74,
    telegramStatus: "mock_sent",
    errorMessage: null,
  },
  {
    id: "run_005",
    taskId: "task_006",
    status: "failed",
    startedAt: minutesAgo(240),
    finishedAt: minutesAgo(239),
    rawInput: {},
    gptPrompt: "Summarize football match results from Football API.",
    gptOutput: {
      title: "Football Recap Failed",
      summary: "ไม่สามารถดึงข้อมูลจาก Football API mock ได้ในรอบนี้",
      priority_score: 20,
      recommended_action: "ตรวจสอบ API key หรือ mock provider ก่อนรันใหม่",
      caption: null,
      image_prompt: null,
    },
    priorityScore: 20,
    telegramStatus: "skipped",
    errorMessage: "FOOTBALL_API_MOCK_TIMEOUT",
  },
  {
    id: "run_006",
    taskId: "task_005",
    status: "success",
    startedAt: minutesAgo(2880),
    finishedAt: minutesAgo(2879),
    rawInput: {
      concerts: ["Indie Night Bangkok", "Synth Pop Live", "Jazz Weekend"],
    },
    gptPrompt: "Summarize new concert announcements and recommend actions.",
    gptOutput: {
      title: "Concert Alerts",
      summary: "มีคอนเสิร์ตที่น่าสนใจใกล้กรุงเทพ 3 รายการ เหมาะกับการบันทึกไว้ดูต่อ",
      priority_score: 78,
      recommended_action: "เลือกศิลปินที่สนใจแล้วตั้ง reminder สำหรับวันขายบัตร",
      caption: "คอนเสิร์ตน่าไปประจำสัปดาห์ มาแล้ว!",
      image_prompt: "9:16 neon concert alert poster, dark glass UI, purple blue light, Bangkok music vibe",
    },
    priorityScore: 78,
    telegramStatus: "not_enabled",
    errorMessage: null,
  },
  {
    id: "run_007",
    taskId: "task_007",
    status: "success",
    startedAt: minutesAgo(3000),
    finishedAt: minutesAgo(2998),
    rawInput: {
      articles: ["Long read about AI agents", "Deep dive on productivity systems"],
    },
    gptPrompt: "Pick weekend long reads and explain why they are worth reading.",
    gptOutput: {
      title: "Weekend Long Read Picks",
      summary: "คัดบทความอ่านยาว 2 เรื่องเกี่ยวกับ AI agents และ productivity systems เหมาะกับอ่านวันหยุด",
      priority_score: 69,
      recommended_action: "บันทึกบทความไว้ใน weekend reading list",
      caption: "บทความอ่านยาววันหยุด: AI agents + productivity systems",
      image_prompt: "9:16 cozy long read card, dark neon SaaS dashboard, blue purple glow, reading list UI",
    },
    priorityScore: 69,
    telegramStatus: "not_enabled",
    errorMessage: null,
  },
];

export const webNotifications: WebNotification[] = [
  {
    id: "noti_001",
    userId: "user_001",
    taskId: "task_004",
    taskRunId: "run_003",
    title: "มีอีเมลสำคัญต้องดู",
    summary: "GPT พบ Security alert และ invoice reminder ที่ควรตรวจวันนี้ Priority 88/100",
    type: "Email Monitor",
    priorityScore: 88,
    isRead: false,
    createdAt: minutesAgo(34),
  },
  {
    id: "noti_002",
    userId: "user_001",
    taskId: "task_001",
    taskRunId: "run_001",
    title: "Morning Daily Brief พร้อมแล้ว",
    summary: "GPT สรุปข่าว AI และสภาพอากาศให้แล้ว Priority 82/100",
    type: "Daily Brief",
    priorityScore: 82,
    isRead: false,
    createdAt: minutesAgo(78),
  },
  {
    id: "noti_003",
    userId: "user_001",
    taskId: "task_003",
    taskRunId: "run_004",
    title: "Weekend Ideas พร้อมใช้",
    summary: "แนะนำคาเฟ่ช่วงเช้าและกิจกรรม outdoor พร้อม prompt ภาพ 9:16",
    type: "Weekend Ideas",
    priorityScore: 74,
    isRead: true,
    createdAt: minutesAgo(1438),
  },
  {
    id: "noti_004",
    userId: "user_001",
    taskId: "task_006",
    taskRunId: "run_005",
    title: "Football Recap มีปัญหา",
    summary: "Task ดึงข้อมูล Football API mock ไม่สำเร็จ ต้องตรวจสอบก่อนรันใหม่",
    type: "World Cup Recap",
    priorityScore: 20,
    isRead: false,
    createdAt: minutesAgo(239),
  },
  {
    id: "noti_005",
    userId: "user_001",
    taskId: "task_002",
    taskRunId: "run_002",
    title: "Sale Monitor กำลังรัน",
    summary: "ระบบกำลังตรวจสอบราคา power bank, USB-C cable และ wireless earbuds",
    type: "Sale Monitor",
    priorityScore: 52,
    isRead: false,
    createdAt: minutesAgo(4),
  },
  {
    id: "noti_006",
    userId: "user_001",
    taskId: "task_005",
    taskRunId: "run_006",
    title: "พบคอนเสิร์ตน่าสนใจ",
    summary: "มีรายการคอนเสิร์ตใกล้กรุงเทพที่ควรบันทึกไว้ดูต่อ Priority 78/100",
    type: "Concert Alerts",
    priorityScore: 78,
    isRead: true,
    createdAt: minutesAgo(2878),
  },
  {
    id: "noti_007",
    userId: "user_001",
    taskId: "task_007",
    taskRunId: "run_007",
    title: "Weekend Long Read คัดแล้ว",
    summary: "คัดบทความอ่านยาวเกี่ยวกับ AI agents และ productivity systems สำหรับวันหยุด",
    type: "Weekend Long Read",
    priorityScore: 69,
    isRead: true,
    createdAt: minutesAgo(2997),
  },
];
